### ISSUE TITLE
Design / Perf

### ISSUE THREAD

**Issue by builder-main** [llamacademy/light-lod#1]
Nice base thanks for sharing,
It seems overkill for each light to update itself, the Camera script should register all lights and update them. it would furthermore allow for general controls like a max number of light having shadow at a time and camera frustrum coverage priority.

**Comment by llamacademy** [comment]
You are right! Having the lights self-register with a camera (or cameras) would be a much more efficient way of handling things so it's only 1 Update call per camera instead of 1 update per light, and would also allow more interesting additional quality / optimizations that could be added on a camera-by-camera basis. 

I chose this way to make it very clear to follow in the tutorial even for more beginner level developers. I will update the readme with some notes about further optimizations that could be done to make this more efficient and configurable.
